name: Initializing Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::416394563192:role/github-action_deploy_policy
          aws-region: us-east-1

      - name: Upload Files to S3
        run: |
          aws s3 mb s3://416394563192-devops-script --region us-east-1 2>/dev/null || true
          aws s3 cp init.py s3://416394563192-devops-script/init.py
          aws s3 cp init.sql s3://416394563192-devops-script/init.sql
          echo "✅ File Are Uploaded to bucket.."

      - name: Initializing Database on RDS using EC2 
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
          --targets "Key=tag:App,Values=flask" \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":[
          "aws s3 cp s3://416394563192-devops-script/init.py /tmp/init.py",
          "aws s3 cp s3://416394563192-devops-script/init.sql /tmp/init.sql",
          "python3 /tmp/init.py",
          "rm -f /tmp/init.py /tmp/init.sql"
          ]}' \
          --query 'Command.CommandId' \
          --output text \
          --region us-east-1)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT  

      - name: Show Result
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region us-east-1 \
            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,Output:CommandPlugins[0].Output}" \
            --output table

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region us-east-1 \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text)

          echo "Failed Instances: $FAILED"

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::$FAILED instance(s) failed database initialization."
            exit 1
          fi

          echo "✅ Database initialized successfully on all instances."