name: Application Deploying on AWS

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  VERSION: v1
  REGISTRY: 416394563192.dkr.ecr.us-east-1.amazonaws.com
  REPOSITORY: simplebank
  REGION: us-east-1
  S3_BUCKET_NAME: 416394563192-devops-script 
  TARGET_TAG_KEY: App                         
  TARGET_TAG_VALUE: flask                     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: kaushalchauhan84850/2-tear-desployement
          ref: main

      - name: Set Dynamic Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::416394563192:role/github-action_deploy_policy
          aws-region: ${{ env.REGION }}

      - name: Login to ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login --username AWS --password-stdin ${{ env.REGISTRY }}
          echo "Login successfully to ECR ✅"

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          echo "Docker image pushed to ECR successfully! 🚀"

      - name: Upload Docker Compose Configuration to S3
        run: |
          aws s3 cp docker-compose.yml s3://${{ env.S3_BUCKET_NAME }}/docker-compose.yml
          echo "docker-compose.yml synchronized to S3 bucket! 📦"

      - name: Execute Remote Deployment via AWS SSM Tag Targeting
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:${{ env.TARGET_TAG_KEY }},Values=${{ env.TARGET_TAG_VALUE }}" \
            --parameters 'commands=["/home/ubuntu/deploy.sh"]' \
            --comment "Automated tag-targeted deployment pipeline delivery for simplebank" \
            --query "Command.CommandId" \
            --output text)
          
          echo "SSM Tag-Targeted Command triggered successfully. Command ID: $COMMAND_ID"
          echo "Deployment initiated on all target fleet nodes matching ${{ env.TARGET_TAG_KEY }}=${{ env.TARGET_TAG_VALUE }}! ⚡"
